apiVersion: apps/v1
kind: Deployment
metadata:
  name: adjective-deployment
  labels:
    app: adjective
spec:
  replicas: 3
  selector:
    matchLabels:
      app: adjective
  template:
    metadata:
      labels:
        app: adjective
    spec:
      containers:
      - name: adjective-pod
        image: vikrambindal/node-english
        ports:
        - containerPort: 4000
        env:
        - name: WORDS
          value: "reasonable,leaky,suspicious,ordinary,unlikely"
        - name: PORT
          value: "4000"
