apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-deployment
  labels:
    app: article
spec:
  replicas: 3
  selector:
    matchLabels:
      app: article
  template:
    metadata:
      labels:
        app: article
    spec:
      containers:
      - name: article-pod
        image: vikrambindal/node-english
        ports:
        - containerPort: 5000
        env:
        - name: WORDS
          value: "a,the"
        - name: PORT
          value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: article-service
spec:
  type: NodePort
  selector:
    app: article
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30002
