apiVersion: apps/v1
kind: Deployment
metadata:
  name: noun-deployment
  labels:
    app: noun
spec:
  replicas: 3
  selector:
    matchLabels:
      app: noun
  template:
    metadata:
      labels:
        app: noun
    spec:
      containers:
      - name: noun-pod
        image: vikrambindal/node-english
        ports:
        - containerPort: 6000
        env:
        - name: WORDS
          value: "boat,book,vote,seat,backpack,partition,groundhog"
        - name: PORT
          value: "6000"
---
apiVersion: v1
kind: Service
metadata:
  name: noun-service
spec:
  type: NodePort
  selector:
    app: noun
  ports:
  - port: 6000
    targetPort: 6000
    nodePort: 30003
