apiVersion: apps/v1
kind: Deployment
metadata:
  name: subject-deployment
  labels:
    app: subject
spec:
  replicas: 3
  selector:
    matchLabels:
      app: subject
  template:
    metadata:
      labels:
        app: subject
    spec:
      containers:
      - name: subject-pod
        image: vikrambindal/node-english
        ports:
        - containerPort: 7000
        env:
        - name: WORDS
          value: "I,You,He,She,It"
        - name: PORT
          value: "7000"
---
apiVersion: v1
kind: Service
metadata:
  name: subject-service
spec:
  type: NodePort
  selector:
    app: subject
  ports:
  - port: 7000
    targetPort: 7000
    nodePort: 30004
