apiVersion: apps/v1
kind: Deployment
metadata:
  name: verb-deployment
  labels:
    app: verb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: verb
  template:
    metadata:
      labels:
        app: verb
    spec:
      containers:
      - name: verb-pod
        image: vikrambindal/node-english
        ports:
        - containerPort: 8000
        env:
        - name: WORDS
          value: "ran,knew,had,saw,bought"
        - name: PORT
          value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: verb-service
spec:
  type: NodePort
  selector:
    app: verb
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30005
