apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentence-deployment
  labels:
    app: sentence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentence
  template:
    metadata:
      labels:
        app: sentence
    spec:
      containers:
      - name: verb-pod
        image: vikrambindal/node-sentence
        ports:
        - containerPort: 9000
        env:
        - name: ADJECTIVE
          valueFrom:
            configMapKeyRef:
              name: services
              key: ADJECTIVE
        - name: ARTICLE
          valueFrom:
            configMapKeyRef:
              name: services
              key: ARTICLE
        - name: NOUN
          valueFrom:
            configMapKeyRef:
              name: services
              key: NOUN
        - name: SUBJECT
          valueFrom:
            configMapKeyRef:
              name: services
              key: SUBJECT
        - name: VERB
          valueFrom:
            configMapKeyRef:
              name: services
              key: VERB
        - name: PORT
          value: "9000"
---
apiVersion: v1
kind: Service
metadata:
  name: sentence-service
spec:
  type: NodePort
  selector:
    app: sentence
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 30006
